name: Tarea_4

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: docker build server
        run: |
          docker build ./Server -t react-app 
        
      - name: docker build Client
        run: |
          docker build ./client -t node-server
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.0
         
            
